#!/usr/bin/env bun

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { ModelInfo } from "../src/models/schemas/index.js";
import { loadModelsDevProviderModels } from "./models/generate-models-dev";

const OUTPUT_FILE = "src/models/generated.ts";

function sortObjectByKey<T>(
	input: Record<string, T>,
	order: "asc" | "desc" = "asc",
): Record<string, T> {
	return Object.fromEntries(
		Object.entries(input).sort(([a], [b]) =>
			order === "asc" ? a.localeCompare(b) : b.localeCompare(a),
		),
	);
}

async function generate(): Promise<void> {
	const providerModels: Record<string, Record<string, ModelInfo>> = {};

	try {
		const modelsDev = await loadModelsDevProviderModels();
		Object.assign(providerModels, modelsDev);
	} catch (error) {
		console.warn(
			`Warning: failed to fetch models.dev: ${error instanceof Error ? error.message : String(error)}`,
		);
	}

	const sortedProviders = sortObjectByKey(providerModels);
	const output = `/**
 * Auto-generated model catalog.
 *
 * WARNING: DO NOT EDIT THIS FILE MANUALLY.
 *
 * Generated by: @cline/llms/scripts/generate-models.ts
 * Inputs:
 * - ./scripts/generate-models-dev.ts
 */

import type { ModelInfo } from "./schemas/index.js"

export const GENERATED_PROVIDER_MODELS: Record<string, Record<string, ModelInfo>> = ${JSON.stringify(sortedProviders, null, 2)}
`;

	const __filename = fileURLToPath(import.meta.url);
	const __dirname = dirname(__filename);
	const root = join(__dirname, "..");
	const outputPath = join(root, OUTPUT_FILE);

	mkdirSync(dirname(outputPath), { recursive: true });
	writeFileSync(outputPath, output, "utf8");

	const totalModels = Object.values(sortedProviders).reduce(
		(count, models) => count + Object.keys(models).length,
		0,
	);
	console.log(`Generated ${OUTPUT_FILE}`);
	console.log(`Providers: ${Object.keys(sortedProviders).length}`);
	console.log(`Models: ${totalModels}`);
}

generate().catch((error) => {
	console.error(error instanceof Error ? error.message : String(error));
	process.exitCode = 1;
});
